import type { CompanyProfile, Employee, PayrollItem, PayrollRun } from "@/modules/hrm/model";
import { getTenantBranding } from "@/modules/reporting/services/tenant-branding";
import {
  applyTenantPdfFooter,
  createTenantPdf,
  writeKeyValueRows,
  writeTable,
  writeWrappedText
} from "@/modules/reporting/services/tenant-pdf";

function money(n: number) {
  return new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", maximumFractionDigits: 0 }).format(n);
}

function periodLabel(period: string) {
  const [y, m] = period.split("-").map(Number);
  if (!y || !m) return period;
  return new Date(y, m - 1, 1).toLocaleString("en-PK", { month: "long", year: "numeric" });
}

export function downloadSalarySlip(opts: {
  company?: CompanyProfile | null;
  employee: Employee;
  run: PayrollRun;
  item: PayrollItem;
}) {
  const { employee, run, item } = opts;
  const branding = getTenantBranding(employee.tenant_id);
  const ctx = createTenantPdf(branding, `Salary Slip · ${periodLabel(run.period)}`);

  let y = writeKeyValueRows(ctx, ctx.contentStartY, [
    ["Employee", employee.full_name],
    ["Employee No", employee.employee_no],
    ["CNIC", employee.cnic ?? "—"],
    ["Bank", `${employee.bank_name ?? "—"}  /  ${employee.bank_account ?? "—"}`],
    ["Period", periodLabel(run.period)]
  ]);

  y += 6;
  const rows: Array<[string, string]> = [["Basic salary", money(item.basic)]];
  if (item.housing != null) rows.push(["Housing allowance", money(item.housing)]);
  if (item.transport != null) rows.push(["Transport allowance", money(item.transport)]);
  if (item.medical != null) rows.push(["Medical allowance", money(item.medical)]);
  if (item.housing == null && item.transport == null && item.medical == null) {
    rows.push(["Allowances", money(item.allowances)]);
  } else {
    const other = item.allowances - (item.housing ?? 0) - (item.transport ?? 0) - (item.medical ?? 0);
    if (other > 0) rows.push(["Other allowance", money(other)]);
  }
  if (item.overtime_pay) rows.push([`Overtime (${item.overtime_hours ?? 0}h × 1.5)`, money(item.overtime_pay)]);
  if (item.tax != null) rows.push(["Income tax", money(item.tax)]);
  if (item.benefits) rows.push(["Benefit premiums", money(item.benefits)]);
  if (item.eobi != null) rows.push(["EOBI", money(item.eobi)]);
  if (item.loan_deduction) rows.push(["Loan recovery", money(item.loan_deduction)]);
  if (item.lwp_amount) rows.push([`Leave without pay (${item.lwp_days ?? 0}d)`, money(item.lwp_amount)]);
  rows.push(
    ["Provident Fund", money(item.pf)],
    ["Net pay", money(item.net)]
  );
  y = writeTable(ctx, y, ["Component", "Amount"], rows);

  y += 8;
  ctx.doc.setFont("helvetica", "normal");
  ctx.doc.setTextColor(100, 110, 125);
  writeWrappedText(ctx, "Generated by BusinessSuite ERP · For employee records.", y, { fontSize: 8 });

  applyTenantPdfFooter(ctx);
  ctx.doc.save(`salary-slip-${employee.employee_no}-${run.period}.pdf`);
}

export function downloadBankLetter(opts: {
  company?: CompanyProfile | null;
  run: PayrollRun;
  items: Array<{ employee: Employee; item: PayrollItem }>;
}) {
  const { run, items } = opts;
  const branding = getTenantBranding(run.tenant_id);
  const ctx = createTenantPdf(branding, "Salary Disbursement Letter");
  const today = new Date().toLocaleDateString("en-PK", { year: "numeric", month: "long", day: "numeric" });
  const total = items.reduce((sum, row) => sum + row.item.net, 0);

  let y = writeKeyValueRows(ctx, ctx.contentStartY, [
    ["Date", today],
    ["To", "The Branch Manager"],
    ["Subject", `Salary transfer for ${periodLabel(run.period)}`]
  ]);

  y += 4;
  y = writeWrappedText(
    ctx,
    `Please debit our account and credit the following employee bank accounts for payroll period ${periodLabel(run.period)}. Total net amount: ${money(total)}.`,
    y
  );

  y += 6;
  y = writeTable(
    ctx,
    y,
    ["Name", "Account", "Bank", "Net"],
    items.map((row) => [
      row.employee.full_name,
      row.employee.bank_account ?? "—",
      row.employee.bank_name ?? "—",
      money(row.item.net)
    ])
  );

  y += 12;
  ctx.doc.setFont("helvetica", "normal");
  ctx.doc.setTextColor(20, 24, 33);
  y = writeWrappedText(ctx, "Authorized Signatory", y);
  y += 10;
  y = writeWrappedText(ctx, "________________________", y);
  writeWrappedText(ctx, branding.legalName, y + 4);

  applyTenantPdfFooter(ctx);
  ctx.doc.save(`bank-letter-${run.period}.pdf`);
}
