/** Stable form keys for tenant extra-field schemas (one schema per tenant + form). */

export type ExtraFormCatalogItem = {
  key: string;
  label: string;
  module: string;
};

export const EXTRA_FORM_CATALOG: ExtraFormCatalogItem[] = [
  { key: "crm.lead", label: "CRM · Lead", module: "CRM" },
  { key: "crm.customer", label: "CRM · Customer", module: "CRM" },
  { key: "crm.contact", label: "CRM · Contact", module: "CRM" },
  { key: "crm.deal", label: "CRM · Deal", module: "CRM" },
  { key: "crm.activity", label: "CRM · Activity", module: "CRM" },
  { key: "crm.campaign", label: "CRM · Campaign", module: "CRM" },
  { key: "crm.ticket", label: "CRM · Ticket", module: "CRM" },
  { key: "crm.customer_group", label: "CRM · Customer group", module: "CRM" },

  { key: "sales.quotation", label: "Sales · Quotation", module: "Sales" },
  { key: "sales.order", label: "Sales · Sales order", module: "Sales" },
  { key: "sales.invoice", label: "Sales · Invoice", module: "Sales" },
  { key: "sales.payment", label: "Sales · Payment received", module: "Sales" },
  { key: "sales.return", label: "Sales · Sales return", module: "Sales" },
  { key: "sales.delivery", label: "Sales · Delivery note", module: "Sales" },
  { key: "sales.credit_note", label: "Sales · Credit note", module: "Sales" },
  { key: "sales.price_list", label: "Sales · Price list", module: "Sales" },
  { key: "sales.salesperson", label: "Sales · Salesperson", module: "Sales" },

  { key: "purchases.supplier", label: "Purchases · Supplier", module: "Purchases" },
  { key: "purchases.order", label: "Purchases · Purchase order", module: "Purchases" },
  { key: "purchases.receipt", label: "Purchases · Goods receipt", module: "Purchases" },
  { key: "purchases.bill", label: "Purchases · Vendor bill", module: "Purchases" },
  { key: "purchases.payment", label: "Purchases · Payment made", module: "Purchases" },
  { key: "purchases.requisition", label: "Purchases · Requisition", module: "Purchases" },
  { key: "purchases.rfq", label: "Purchases · RFQ", module: "Purchases" },

  { key: "inventory.product", label: "Inventory · Product", module: "Inventory" },
  { key: "inventory.category", label: "Inventory · Category", module: "Inventory" },
  { key: "inventory.warehouse", label: "Inventory · Warehouse", module: "Inventory" },
  { key: "inventory.movement", label: "Inventory · Stock movement", module: "Inventory" },
  { key: "inventory.transfer", label: "Inventory · Transfer", module: "Inventory" },
  { key: "inventory.adjustment", label: "Inventory · Adjustment", module: "Inventory" },
  { key: "inventory.uom", label: "Inventory · Unit of measure", module: "Inventory" },
  { key: "inventory.batch", label: "Inventory · Batch / lot", module: "Inventory" },
  { key: "inventory.serial", label: "Inventory · Serial number", module: "Inventory" },
  { key: "inventory.bin", label: "Inventory · Bin", module: "Inventory" },
  { key: "inventory.brand", label: "Inventory · Brand", module: "Inventory" },

  { key: "purchases.debit_note", label: "Purchases · Debit note", module: "Purchases" },

  { key: "finance.account", label: "Finance · Chart of accounts", module: "Finance" },
  { key: "finance.expense", label: "Finance · Expense", module: "Finance" },
  { key: "finance.income", label: "Finance · Income", module: "Finance" },
  { key: "finance.journal", label: "Finance · Journal", module: "Finance" },
  { key: "finance.tax", label: "Finance · Tax", module: "Finance" },
  { key: "finance.bank", label: "Finance · Bank", module: "Finance" },
  { key: "finance.bank_account", label: "Finance · Bank account", module: "Finance" },
  { key: "finance.cheque", label: "Finance · Cheque / PDC", module: "Finance" },
  { key: "finance.reconciliation", label: "Finance · Bank reconciliation", module: "Finance" },
  { key: "finance.fiscal_year", label: "Finance · Fiscal year", module: "Finance" },
  { key: "finance.period", label: "Finance · Accounting period", module: "Finance" },
  { key: "finance.budget", label: "Finance · Budget", module: "Finance" },
  { key: "finance.voucher_type", label: "Finance · Voucher type", module: "Finance" },
  { key: "finance.withholding", label: "Finance · Withholding certificate", module: "Finance" },
  { key: "finance.currency", label: "Finance · Currency", module: "Finance" },
  { key: "finance.payment_term", label: "Finance · Payment term", module: "Finance" },
  { key: "finance.partner", label: "Finance · Finance partner", module: "Finance" },

  { key: "operations.bom", label: "Operations · Bill of materials", module: "Operations" },
  { key: "operations.work_order", label: "Operations · Work order", module: "Operations" },
  { key: "operations.maintenance", label: "Operations · Maintenance order", module: "Operations" },
  { key: "operations.inspection", label: "Operations · Quality inspection", module: "Operations" },
  { key: "operations.contract", label: "Operations · Contract", module: "Operations" },
  { key: "operations.fleet", label: "Operations · Vehicle / fleet", module: "Operations" },
  { key: "operations.warranty", label: "Operations · Warranty claim", module: "Operations" },

  { key: "healthcare.patient", label: "Healthcare · Patient", module: "Healthcare" },
  { key: "healthcare.doctor", label: "Healthcare · Doctor", module: "Healthcare" },
  { key: "healthcare.appointment", label: "Healthcare · Appointment", module: "Healthcare" },
  { key: "healthcare.opd", label: "Healthcare · OPD visit", module: "Healthcare" },
  { key: "healthcare.ward", label: "Healthcare · Ward", module: "Healthcare" },
  { key: "healthcare.bed", label: "Healthcare · Bed", module: "Healthcare" },
  { key: "healthcare.admission", label: "Healthcare · IPD admission", module: "Healthcare" },
  { key: "healthcare.emergency", label: "Healthcare · Emergency case", module: "Healthcare" },
  { key: "healthcare.prescription", label: "Healthcare · Prescription", module: "Healthcare" },
  { key: "healthcare.pharmacy", label: "Healthcare · Pharmacy item", module: "Healthcare" },
  { key: "healthcare.dispense", label: "Healthcare · Dispensing", module: "Healthcare" },
  { key: "healthcare.lab_test", label: "Healthcare · Lab test", module: "Healthcare" },
  { key: "healthcare.lab_order", label: "Healthcare · Lab order", module: "Healthcare" },
  { key: "healthcare.radiology", label: "Healthcare · Radiology order", module: "Healthcare" },
  { key: "healthcare.diagnosis", label: "Healthcare · Diagnosis", module: "Healthcare" },
  { key: "healthcare.emr", label: "Healthcare · EMR note", module: "Healthcare" },
  { key: "healthcare.ot", label: "Healthcare · OT / surgery", module: "Healthcare" },
  { key: "healthcare.nursing", label: "Healthcare · Nursing note", module: "Healthcare" },
  { key: "healthcare.vital", label: "Healthcare · Vital", module: "Healthcare" },
  { key: "healthcare.treatment_plan", label: "Healthcare · Treatment plan", module: "Healthcare" },
  { key: "healthcare.consent", label: "Healthcare · Consent", module: "Healthcare" },
  { key: "healthcare.insurance", label: "Healthcare · Insurance policy", module: "Healthcare" },
  { key: "healthcare.claim", label: "Healthcare · Insurance claim", module: "Healthcare" },
  { key: "healthcare.infection", label: "Healthcare · Infection incident", module: "Healthcare" },
  { key: "healthcare.quality", label: "Healthcare · Quality incident", module: "Healthcare" },
  { key: "healthcare.equipment", label: "Healthcare · Biomedical equipment", module: "Healthcare" },
  { key: "healthcare.roster", label: "Healthcare · Duty roster", module: "Healthcare" },
  { key: "healthcare.cssd", label: "Healthcare · CSSD log", module: "Healthcare" },
  { key: "healthcare.phc_audit", label: "Healthcare · PHC audit", module: "Healthcare" },

  { key: "projects.project", label: "Projects · Project", module: "Projects" },
  { key: "projects.task", label: "Projects · Task", module: "Projects" },
  { key: "projects.timesheet", label: "Projects · Timesheet", module: "Projects" },

  { key: "hrm.employee", label: "HRM · Employee", module: "HRM" },
  { key: "hrm.candidate", label: "HRM · Candidate", module: "HRM" },
  { key: "hrm.department", label: "HRM · Department", module: "HRM" },
  { key: "hrm.designation", label: "HRM · Designation", module: "HRM" },
  { key: "hrm.disciplinary", label: "HRM · Disciplinary", module: "HRM" },
  { key: "hrm.attendance", label: "HRM · Attendance", module: "HRM" },
  { key: "hrm.timesheet", label: "HRM · Timesheet", module: "HRM" },
  { key: "hrm.leave_request", label: "HRM · Leave request", module: "HRM" },
  { key: "hrm.leave_type", label: "HRM · Leave type", module: "HRM" },
  { key: "hrm.shift", label: "HRM · Shift", module: "HRM" },
  { key: "hrm.holiday", label: "HRM · Holiday", module: "HRM" },
  { key: "hrm.payroll", label: "HRM · Payroll", module: "HRM" },
  { key: "hrm.compensation", label: "HRM · Compensation", module: "HRM" },
  { key: "hrm.my_pay", label: "HRM · My pay", module: "HRM" },
  { key: "hrm.location", label: "HRM · Location", module: "HRM" },
  { key: "hrm.cost_center", label: "HRM · Cost center", module: "HRM" },
  { key: "hrm.job_family", label: "HRM · Job family", module: "HRM" },
  { key: "hrm.job_profile", label: "HRM · Job profile", module: "HRM" },
  { key: "hrm.position", label: "HRM · Position", module: "HRM" },
  { key: "hrm.job_change", label: "HRM · Job change", module: "HRM" },
  { key: "hrm.inbox", label: "HRM · Inbox", module: "HRM" },
  { key: "hrm.benefit_plan", label: "HRM · Benefit plan", module: "HRM" },
  { key: "hrm.benefit_enrollment", label: "HRM · Benefit enrollment", module: "HRM" },
  { key: "hrm.pay_grade", label: "HRM · Pay grade", module: "HRM" },
  { key: "hrm.goal", label: "HRM · Goal", module: "HRM" },
  { key: "hrm.review", label: "HRM · Performance review", module: "HRM" },
  { key: "hrm.requisition", label: "HRM · Job requisition", module: "HRM" },
  { key: "hrm.dependent", label: "HRM · Dependent", module: "HRM" },
  { key: "hrm.identity", label: "HRM · Identity document", module: "HRM" },
  { key: "hrm.education", label: "HRM · Education", module: "HRM" },
  { key: "hrm.experience", label: "HRM · Experience", module: "HRM" },
  { key: "hrm.certification", label: "HRM · Certification", module: "HRM" },
  { key: "hrm.payment_election", label: "HRM · Payment election", module: "HRM" },
  { key: "hrm.costing", label: "HRM · Costing allocation", module: "HRM" },
  { key: "hrm.loan", label: "HRM · Loan", module: "HRM" },
  { key: "hrm.asset", label: "HRM · Asset", module: "HRM" },
  { key: "hrm.announcement", label: "HRM · Announcement", module: "HRM" },
  { key: "hrm.payout", label: "HRM · Salary payout", module: "HRM" },
  { key: "hrm.company", label: "HRM · Company profile", module: "HRM" },
  { key: "hrm.workflow", label: "HRM · Workflow", module: "HRM" },

  { key: "documents.type", label: "Documents · Document type", module: "Documents" },
  { key: "documents.assign", label: "Documents · Assign type", module: "Documents" },

  { key: "settings.tenant", label: "Admin · Company / tenant", module: "Administration" },
  { key: "settings.user", label: "Admin · User", module: "Administration" },
  { key: "dashboard.profile", label: "Dashboard · My profile", module: "Dashboard" },
  { key: "settings.role", label: "Admin · Role", module: "Administration" },
  { key: "settings.blog", label: "Admin · Blog post", module: "Administration" },
  { key: "settings.cms_menu", label: "Admin · CMS menu", module: "Administration" },
  { key: "settings.cms_page", label: "Admin · CMS page", module: "Administration" },
  { key: "settings.system", label: "Admin · System settings", module: "Administration" },
  { key: "billing.package", label: "Billing · Subscription package", module: "Billing" },
  { key: "billing.company", label: "Billing · Company profile", module: "Billing" }
];

export function getExtraFormLabel(formKey: string) {
  return EXTRA_FORM_CATALOG.find((f) => f.key === formKey)?.label ?? formKey;
}
